### PR TITLE
Add updateEmployee Controller method

### PR DESCRIPTION
**Pull request by Ayala1302**
Added updateEmployee Controller method/route.

### CODE REVIEW

**Review by JesusAParedes — CHANGES_REQUESTED** [review]
Looks like you forgot to git pull and merge the main with your branch before creating the pull request. You will have to update that before it gets merged so it doesn't overwrite the main branch.

**Review by JesusAParedes — CHANGES_REQUESTED** [review]
For line 38, you might have to add something instead leaving those first two blank. Such as when the client is updating, from where in "req" are they grabbing for first name and last name? At least I would think so right in order to update the employee?

**Comment by ethan-w-foshee** [comment]
@Ayala1302 ^ You might want to read through these.

**Review by ethan-w-foshee — APPROVED** [review]

**Review by JesusAParedes — CHANGES_REQUESTED** [review]
@Ayala1302 you might want to look at line 57 for the first two parts of rep. I think it would be something similar to req.params.id but references the first name or last name the person puts in their request.

**Review by JesusAParedes — APPROVED** [review]

**Pull request merged**
